<?php
/**
 * IntegrationTransform
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * IntegrationTransform Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IntegrationTransform implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'field' => 'string',
        'regex' => 'string',
        'refs' => 'string[]',
        'example' => '\Swagger\Client\Model\IntegrationTransformExample'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'field' => 'field',
        'regex' => 'regex',
        'refs' => 'refs',
        'example' => 'example'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'field' => 'setField',
        'regex' => 'setRegex',
        'refs' => 'setRefs',
        'example' => 'setExample'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'field' => 'getField',
        'regex' => 'getRegex',
        'refs' => 'getRefs',
        'example' => 'getExample'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $field 
      * @var string
      */
    protected $field;
    
    /**
      * $regex 
      * @var string
      */
    protected $regex;
    
    /**
      * $refs 
      * @var string[]
      */
    protected $refs;
    
    /**
      * $example 
      * @var \Swagger\Client\Model\IntegrationTransformExample
      */
    protected $example;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->field = $data["field"];
            $this->regex = $data["regex"];
            $this->refs = $data["refs"];
            $this->example = $data["example"];
        }
    }
    
    /**
     * Gets field
     * @return string
     */
    public function getField()
    {
        return $this->field;
    }
  
    /**
     * Sets field
     * @param string $field 
     * @return $this
     */
    public function setField($field)
    {
        
        $this->field = $field;
        return $this;
    }
    
    /**
     * Gets regex
     * @return string
     */
    public function getRegex()
    {
        return $this->regex;
    }
  
    /**
     * Sets regex
     * @param string $regex 
     * @return $this
     */
    public function setRegex($regex)
    {
        
        $this->regex = $regex;
        return $this;
    }
    
    /**
     * Gets refs
     * @return string[]
     */
    public function getRefs()
    {
        return $this->refs;
    }
  
    /**
     * Sets refs
     * @param string[] $refs 
     * @return $this
     */
    public function setRefs($refs)
    {
        
        $this->refs = $refs;
        return $this;
    }
    
    /**
     * Gets example
     * @return \Swagger\Client\Model\IntegrationTransformExample
     */
    public function getExample()
    {
        return $this->example;
    }
  
    /**
     * Sets example
     * @param \Swagger\Client\Model\IntegrationTransformExample $example 
     * @return $this
     */
    public function setExample($example)
    {
        
        $this->example = $example;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
