<?php
/**
 * Lti1IntegrationAttributes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * Lti1IntegrationAttributes Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Lti1IntegrationAttributes implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'consumer_key' => 'string',
        'shared_secret' => 'string',
        'taught_unit_type' => 'string',
        'transforms' => '\Swagger\Client\Model\IntegrationTransform[]'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'consumer_key' => 'consumer_key',
        'shared_secret' => 'shared_secret',
        'taught_unit_type' => 'taught_unit_type',
        'transforms' => 'transforms'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'consumer_key' => 'setConsumerKey',
        'shared_secret' => 'setSharedSecret',
        'taught_unit_type' => 'setTaughtUnitType',
        'transforms' => 'setTransforms'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'consumer_key' => 'getConsumerKey',
        'shared_secret' => 'getSharedSecret',
        'taught_unit_type' => 'getTaughtUnitType',
        'transforms' => 'getTransforms'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $consumer_key 
      * @var string
      */
    protected $consumer_key;
    
    /**
      * $shared_secret 
      * @var string
      */
    protected $shared_secret;
    
    /**
      * $taught_unit_type 
      * @var string
      */
    protected $taught_unit_type;
    
    /**
      * $transforms 
      * @var \Swagger\Client\Model\IntegrationTransform[]
      */
    protected $transforms;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->consumer_key = $data["consumer_key"];
            $this->shared_secret = $data["shared_secret"];
            $this->taught_unit_type = $data["taught_unit_type"];
            $this->transforms = $data["transforms"];
        }
    }
    
    /**
     * Gets consumer_key
     * @return string
     */
    public function getConsumerKey()
    {
        return $this->consumer_key;
    }
  
    /**
     * Sets consumer_key
     * @param string $consumer_key 
     * @return $this
     */
    public function setConsumerKey($consumer_key)
    {
        
        $this->consumer_key = $consumer_key;
        return $this;
    }
    
    /**
     * Gets shared_secret
     * @return string
     */
    public function getSharedSecret()
    {
        return $this->shared_secret;
    }
  
    /**
     * Sets shared_secret
     * @param string $shared_secret 
     * @return $this
     */
    public function setSharedSecret($shared_secret)
    {
        
        $this->shared_secret = $shared_secret;
        return $this;
    }
    
    /**
     * Gets taught_unit_type
     * @return string
     */
    public function getTaughtUnitType()
    {
        return $this->taught_unit_type;
    }
  
    /**
     * Sets taught_unit_type
     * @param string $taught_unit_type 
     * @return $this
     */
    public function setTaughtUnitType($taught_unit_type)
    {
        
        $this->taught_unit_type = $taught_unit_type;
        return $this;
    }
    
    /**
     * Gets transforms
     * @return \Swagger\Client\Model\IntegrationTransform[]
     */
    public function getTransforms()
    {
        return $this->transforms;
    }
  
    /**
     * Sets transforms
     * @param \Swagger\Client\Model\IntegrationTransform[] $transforms 
     * @return $this
     */
    public function setTransforms($transforms)
    {
        
        $this->transforms = $transforms;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
