<?php
/**
 * HierarchyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * HierarchyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HierarchyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for addNode
     *
     * 
     *
     */
    public function test_addNode() {

    }
    
    /**
     * Test case for bulkUpload
     *
     * 
     *
     */
    public function test_bulkUpload() {

    }
    
    /**
     * Test case for deleteNode
     *
     * 
     *
     */
    public function test_deleteNode() {

    }
    
    /**
     * Test case for deleteNodes
     *
     * Delete nodes
     *
     */
    public function test_deleteNodes() {

    }
    
    /**
     * Test case for exportHierarchy
     *
     * 
     *
     */
    public function test_exportHierarchy() {

    }
    
    /**
     * Test case for getAncestors
     *
     * Get ancestor nodes
     *
     */
    public function test_getAncestors() {

    }
    
    /**
     * Test case for getChildren
     *
     * Get child nodes
     *
     */
    public function test_getChildren() {

    }
    
    /**
     * Test case for getDescendants
     *
     * Get descendant nodes
     *
     */
    public function test_getDescendants() {

    }
    
    /**
     * Test case for getNode
     *
     * 
     *
     */
    public function test_getNode() {

    }
    
    /**
     * Test case for getParents
     *
     * Get parent nodes
     *
     */
    public function test_getParents() {

    }
    
    /**
     * Test case for replaceNode
     *
     * 
     *
     */
    public function test_replaceNode() {

    }
    
    /**
     * Test case for searchNodes
     *
     * Search nodes
     *
     */
    public function test_searchNodes() {

    }
    
    /**
     * Test case for updateNode
     *
     * 
     *
     */
    public function test_updateNode() {

    }
    
}
